name: ImagesPlus
favicon: null
layout_spectrum: 0.57459
typography_spectrum: 0.47688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#93c235'
    - '#403e39'
    - '#bbbbbb'
    - '#7d7d7d'
  brandStrength: 0.3125
  lightness: 0.6816355760674924
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
