name: ImagesPlus
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#807100'
    - '#a59000'
    - '#b3b09e'
    - '#63635d'
  brandStrength: 0.3125
  lightness: 0.6816355760674924
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
